name: Slack PR Message

on: pull_request

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  - name: Send GitHub Action trigger data to Slack workflow
    id: slack
    uses: slackapi/slack-github-action@v1.14.0
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
